In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
app=pd.read_csv('application_record.csv')
app

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438552,6840104,M,N,Y,0,135000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,-22717,365243,1,0,0,0,NaN,1.0
438553,6840222,F,N,N,0,103500.0,Working,Secondary / secondary special,Single / not married,House / apartment,-15939,-3007,1,0,0,0,Laborers,1.0
438554,6841878,F,N,N,0,54000.0,Commercial associate,Higher education,Single / not married,With parents,-8169,-372,1,1,0,0,Sales staff,1.0
438555,6842765,F,N,Y,0,72000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-21673,365243,1,0,0,0,NaN,2.0
438556,6842885,F,N,Y,0,121500.0,Working,Secondary / secondary special,Married,House / apartment,-18858,-1201,1,0,1,0,Sales staff,2.0

In [3]:
credit=pd.read_csv('credit_record.csv')
credit

              ID  MONTHS_BALANCE STATUS
0        5001711               0      X
1        5001711              -1      0
2        5001711              -2      0
3        5001711              -3      0
4        5001712               0      C
...          ...             ...    ...
1048570  5150487             -25      C
1048571  5150487             -26      C
1048572  5150487             -27      C
1048573  5150487             -28      C
1048574  5150487             -29      C

[1048575 rows x 3 columns]

In [4]:
app.info

<bound method DataFrame.info of              ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
0       5008804           M            Y               Y             0
1       5008805           M            Y               Y             0
2       5008806           M            Y               Y             0
3       5008808           F            N               Y             0
4       5008809           F            N               Y             0
...         ...         ...          ...             ...           ...
438552  6840104           M            N               Y             0
438553  6840222           F            N               N             0
438554  6841878           F            N               N             0
438555  6842765           F            N               Y             0
438556  6842885           F            N               Y             0

        AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \
0               427500.0               Working               Higher education
1               427500.0               Working               Higher education
2               112500.0               Working  Secondary / secondary special
3               270000.0  Commercial associate  Secondary / secondary special
4               270000.0  Commercial associate  Secondary / secondary special
...                  ...                   ...                            ...
438552          135000.0             Pensioner  Secondary / secondary special
438553          103500.0               Working  Secondary / secondary special
438554           54000.0  Commercial associate               Higher education
438555           72000.0             Pensioner  Secondary / secondary special
438556          121500.0               Working  Secondary / secondary special

          NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0             Civil marriage   Rented apartment      -12005          -4542
1             Civil marriage   Rented apartment      -12005          -4542
2                    Married  House / apartment      -21474          -1134
3       Single / not married  House / apartment      -19110          -3051
4       Single / not married  House / apartment      -19110          -3051
...                      ...                ...         ...            ...
438552             Separated  House / apartment      -22717         365243
438553  Single / not married  House / apartment      -15939          -3007
438554  Single / not married       With parents       -8169           -372
438555               Married  House / apartment      -21673         365243
438556               Married  House / apartment      -18858          -1201

        FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL OCCUPATION_TYPE  \
0                1                1           0           0             NaN
1                1                1           0           0             NaN
2                1                0           0           0  Security staff
3                1                0           1           1     Sales staff
4                1                0           1           1     Sales staff
...            ...              ...         ...         ...             ...
438552           1                0           0           0             NaN
438553           1                0           0           0        Laborers
438554           1                1           0           0     Sales staff
438555           1                0           0           0             NaN
438556           1                0           1           0     Sales staff

        CNT_FAM_MEMBERS
0                   2.0
1                   2.0
2                   2.0
3                   1.0
4                   1.0
...                 ...
438552              1.0
438553              1.0
438554              1.0
438555              2.0
438556              2.0

[438557 rows x 18 columns]>

In [5]:
total=app.isnull().sum().sort_values(ascending=False)
percent=(app.isnull().sum()/app.isnull().count()).sort_values(ascending=False)
missing_data=pd.concat([total,percent], axis=1, keys=['Total','Percent'])
missing_data

                      Total  Percent
OCCUPATION_TYPE      134203  0.30601
ID                        0  0.00000
CODE_GENDER               0  0.00000
FLAG_OWN_CAR              0  0.00000
CNT_CHILDREN              0  0.00000
FLAG_OWN_REALTY           0  0.00000
NAME_INCOME_TYPE          0  0.00000
NAME_EDUCATION_TYPE       0  0.00000
NAME_FAMILY_STATUS        0  0.00000
AMT_INCOME_TOTAL          0  0.00000
NAME_HOUSING_TYPE         0  0.00000
DAYS_BIRTH                0  0.00000
FLAG_MOBIL                0  0.00000
DAYS_EMPLOYED             0  0.00000
FLAG_WORK_PHONE           0  0.00000
FLAG_PHONE                0  0.00000
FLAG_EMAIL                0  0.00000
CNT_FAM_MEMBERS           0  0.00000

In [6]:
missing_ratio=app['OCCUPATION_TYPE'].isna().mean()
missing_ratio

np.float64(0.30601039317580153)

In [7]:
app['OCCUPATION_TYPE'].fillna('Unknown', inplace=True)

C:\Users\Olivia Stefany Can\AppData\Local\Temp\ipykernel_28804\1527723923.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app['OCCUPATION_TYPE'].fillna('Unknown', inplace=True)

In [8]:
app.isna().sum()

ID                     0
CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
dtype: int64

In [9]:
# Label encoding
from sklearn.preprocessing import LabelEncoder
label_encoder= LabelEncoder()
for label in (['CODE_GENDER','FLAG_OWN_CAR','FLAG_OWN_REALTY']):
    app[label]=label_encoder.fit_transform(app[label])
app

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,1,1,1,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Unknown,2.0
1,5008805,1,1,1,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Unknown,2.0
2,5008806,1,1,1,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,0,0,1,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,0,0,1,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438552,6840104,1,0,1,0,135000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,-22717,365243,1,0,0,0,Unknown,1.0
438553,6840222,0,0,0,0,103500.0,Working,Secondary / secondary special,Single / not married,House / apartment,-15939,-3007,1,0,0,0,Laborers,1.0
438554,6841878,0,0,0,0,54000.0,Commercial associate,Higher education,Single / not married,With parents,-8169,-372,1,1,0,0,Sales staff,1.0
438555,6842765,0,0,1,0,72000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-21673,365243,1,0,0,0,Unknown,2.0
438556,6842885,0,0,1,0,121500.0,Working,Secondary / secondary special,Married,House / apartment,-18858,-1201,1,0,1,0,Sales staff,2.0

In [10]:
app.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS'],
      dtype='object')

In [11]:
# One-Hot Encoding
app = pd.get_dummies(app, columns=['NAME_INCOME_TYPE','NAME_EDUCATION_TYPE','NAME_FAMILY_STATUS','NAME_HOUSING_TYPE','OCCUPATION_TYPE'],prefix=['INC','EDU','STATUS','HOUSE','JOB'],drop_first=True)
app

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,...,JOB_Low-skill Laborers,JOB_Managers,JOB_Medicine staff,JOB_Private service staff,JOB_Realty agents,JOB_Sales staff,JOB_Secretaries,JOB_Security staff,JOB_Unknown,JOB_Waiters/barmen staff
0,5008804,1,1,1,0,427500.0,-12005,-4542,1,1,...,False,False,False,False,False,False,False,False,True,False
1,5008805,1,1,1,0,427500.0,-12005,-4542,1,1,...,False,False,False,False,False,False,False,False,True,False
2,5008806,1,1,1,0,112500.0,-21474,-1134,1,0,...,False,False,False,False,False,False,False,True,False,False
3,5008808,0,0,1,0,270000.0,-19110,-3051,1,0,...,False,False,False,False,False,True,False,False,False,False
4,5008809,0,0,1,0,270000.0,-19110,-3051,1,0,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438552,6840104,1,0,1,0,135000.0,-22717,365243,1,0,...,False,False,False,False,False,False,False,False,True,False
438553,6840222,0,0,0,0,103500.0,-15939,-3007,1,0,...,False,False,False,False,False,False,False,False,False,False
438554,6841878,0,0,0,0,54000.0,-8169,-372,1,1,...,False,False,False,False,False,True,False,False,False,False
438555,6842765,0,0,1,0,72000.0,-21673,365243,1,0,...,False,False,False,False,False,False,False,False,True,False
438556,6842885,0,0,1,0,121500.0,-18858,-1201,1,0,...,False,False,False,False,False,True,False,False,False,False

In [12]:
# Standardization ( Logistic-regression model)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
app[['CNT_CHILDREN','AMT_INCOME_TOTAL']]=scaler.fit_transform(app[['CNT_CHILDREN','AMT_INCOME_TOTAL']])

In [13]:
app.head(20)

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,...,JOB_Low-skill Laborers,JOB_Managers,JOB_Medicine staff,JOB_Private service staff,JOB_Realty agents,JOB_Sales staff,JOB_Secretaries,JOB_Security staff,JOB_Unknown,JOB_Waiters/barmen staff
0,5008804,1,1,1,-0.5896,2.179879,-12005,-4542,1,1,...,False,False,False,False,False,False,False,False,True,False
1,5008805,1,1,1,-0.5896,2.179879,-12005,-4542,1,1,...,False,False,False,False,False,False,False,False,True,False
2,5008806,1,1,1,-0.5896,-0.681502,-21474,-1134,1,0,...,False,False,False,False,False,False,False,True,False,False
3,5008808,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,False,False,False,False,True,False,False,False,False
4,5008809,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,False,False,False,False,True,False,False,False,False
5,5008810,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,False,False,False,False,True,False,False,False,False
6,5008811,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,False,False,False,False,True,False,False,False,False
7,5008812,0,0,1,-0.5896,0.871819,-22464,365243,1,0,...,False,False,False,False,False,False,False,False,True,False
8,5008813,0,0,1,-0.5896,0.871819,-22464,365243,1,0,...,False,False,False,False,False,False,False,False,True,False
9,5008814,0,0,1,-0.5896,0.871819,-22464,365243,1,0,...,False,False,False,False,False,False,False,False,True,False
10,5008815,1,1,1,-0.5896,0.749189,-16872,-769,1,1,...,False,False,False,False,False,False,False,False,False,False
11,5112956,1,1,1,-0.5896,0.749189,-16872,-769,1,1,...,False,False,False,False,False,False,False,False,False,False
12,6153651,1,1,1,-0.5896,0.749189,-16872,-769,1,1,...,False,False,False,False,False,False,False,False,False,False
13,5008819,1,1,1,-0.5896,-0.477117,-17778,-1194,1,0,...,False,False,False,False,False,False,False,False,False,False
14,5008820,1,1,1,-0.5896,-0.477117,-17778,-1194,1,0,...,False,False,False,False,False,False,False,False,False,False
15,5008821,1,1,1,-0.5896,-0.477117,-17778,-1194,1,0,...,False,False,False,False,False,False,False,False,False,False
16,5008822,1,1,1,-0.5896,-0.477117,-17778,-1194,1,0,...,False,False,False,False,False,False,False,False,False,False
17,5008823,1,1,1,-0.5896,-0.477117,-17778,-1194,1,0,...,False,False,False,False,False,False,False,False,False,False
18,5008824,1,1,1,-0.5896,-0.477117,-17778,-1194,1,0,...,False,False,False,False,False,False,False,False,False,False
19,5008825,0,1,0,-0.5896,-0.517994,-10669,-1103,1,0,...,False,False,False,False,False,False,False,False,False,False

In [14]:
app = app.drop_duplicates(subset='ID')
app['ID'].duplicated().sum()

np.int64(0)

In [15]:
# aggregation
# turn string into number in credit record dataset

print(credit['STATUS'].unique())
print(credit['STATUS'].dtype)

['X' '0' 'C' '1' '2' '3' '4' '5']
object

In [16]:
credit_map={'0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'X':0,'C':0}
credit['STATUS']=credit['STATUS'].map(credit_map).astype(int)

In [17]:
agg= credit.groupby('ID').agg(
    record_count=('MONTHS_BALANCE','count'), 
    overdue_count=('STATUS',lambda x:(x > 0).sum()),
    overdue_rate=('STATUS', lambda x:(x > 0).mean()),
    worst_status=('STATUS','max')).reset_index()
agg

            ID  record_count  overdue_count  overdue_rate  worst_status
0      5001711             4              0           0.0             0
1      5001712            19              0           0.0             0
2      5001713            22              0           0.0             0
3      5001714            15              0           0.0             0
4      5001715            60              0           0.0             0
...        ...           ...            ...           ...           ...
45980  5150482            18              0           0.0             0
45981  5150483            18              0           0.0             0
45982  5150484            13              0           0.0             0
45983  5150485             2              0           0.0             0
45984  5150487            30              0           0.0             0

[45985 rows x 5 columns]

In [18]:
# merge dataset
final_data=app.merge(agg, on='ID', how='left')
final_data

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,...,JOB_Realty agents,JOB_Sales staff,JOB_Secretaries,JOB_Security staff,JOB_Unknown,JOB_Waiters/barmen staff,record_count,overdue_count,overdue_rate,worst_status
0,5008804,1,1,1,-0.5896,2.179879,-12005,-4542,1,1,...,False,False,False,False,True,False,16.0,1.0,0.062500,1.0
1,5008805,1,1,1,-0.5896,2.179879,-12005,-4542,1,1,...,False,False,False,False,True,False,15.0,1.0,0.066667,1.0
2,5008806,1,1,1,-0.5896,-0.681502,-21474,-1134,1,0,...,False,False,False,True,False,False,30.0,0.0,0.000000,0.0
3,5008808,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,True,False,False,False,False,5.0,0.0,0.000000,0.0
4,5008809,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,True,False,False,False,False,5.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438505,6840104,1,0,1,-0.5896,-0.477117,-22717,365243,1,0,...,False,False,False,False,True,False,NaN,NaN,NaN,NaN
438506,6840222,0,0,0,-0.5896,-0.763255,-15939,-3007,1,0,...,False,False,False,False,False,False,NaN,NaN,NaN,NaN
438507,6841878,0,0,0,-0.5896,-1.212901,-8169,-372,1,1,...,False,True,False,False,False,False,NaN,NaN,NaN,NaN
438508,6842765,0,0,1,-0.5896,-1.049393,-21673,365243,1,0,...,False,False,False,False,True,False,NaN,NaN,NaN,NaN
438509,6842885,0,0,1,-0.5896,-0.599748,-18858,-1201,1,0,...,False,True,False,False,False,False,NaN,NaN,NaN,NaN

In [19]:
final_data=final_data.fillna(0)
final_data

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,...,JOB_Realty agents,JOB_Sales staff,JOB_Secretaries,JOB_Security staff,JOB_Unknown,JOB_Waiters/barmen staff,record_count,overdue_count,overdue_rate,worst_status
0,5008804,1,1,1,-0.5896,2.179879,-12005,-4542,1,1,...,False,False,False,False,True,False,16.0,1.0,0.062500,1.0
1,5008805,1,1,1,-0.5896,2.179879,-12005,-4542,1,1,...,False,False,False,False,True,False,15.0,1.0,0.066667,1.0
2,5008806,1,1,1,-0.5896,-0.681502,-21474,-1134,1,0,...,False,False,False,True,False,False,30.0,0.0,0.000000,0.0
3,5008808,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,True,False,False,False,False,5.0,0.0,0.000000,0.0
4,5008809,0,0,1,-0.5896,0.749189,-19110,-3051,1,0,...,False,True,False,False,False,False,5.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438505,6840104,1,0,1,-0.5896,-0.477117,-22717,365243,1,0,...,False,False,False,False,True,False,0.0,0.0,0.000000,0.0
438506,6840222,0,0,0,-0.5896,-0.763255,-15939,-3007,1,0,...,False,False,False,False,False,False,0.0,0.0,0.000000,0.0
438507,6841878,0,0,0,-0.5896,-1.212901,-8169,-372,1,1,...,False,True,False,False,False,False,0.0,0.0,0.000000,0.0
438508,6842765,0,0,1,-0.5896,-1.049393,-21673,365243,1,0,...,False,False,False,False,True,False,0.0,0.0,0.000000,0.0
438509,6842885,0,0,1,-0.5896,-0.599748,-18858,-1201,1,0,...,False,True,False,False,False,False,0.0,0.0,0.000000,0.0

In [20]:
final_data['TARGET'] = (final_data['worst_status'] > 0).astype(int)

In [32]:
X=final_data.drop(columns =['ID', 'TARGET', 'worst_status', 'overdue_count', 'overdue_rate'])
y=final_data['TARGET']

In [33]:
# Split train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [34]:
print(y.value_counts())

TARGET
0    434219
1      4291
Name: count, dtype: int64

In [35]:
# modelling

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score

models={'Logistic Regression' : LogisticRegression(max_iter=1000),
        'Decision Tree': DecisionTreeClassifier(),
        'Random Forest':RandomForestClassifier()}

for name, model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    y_proba=model.predict_proba(X_test)[:,1]
    print(f"\n{name}")
    print(classification_report(y_test,y_pred))
    print('ROC', roc_auc_score(y_test,y_proba))

Logistic Regression
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     86844
           1       0.18      0.02      0.04       858

    accuracy                           0.99     87702
   macro avg       0.59      0.51      0.52     87702
weighted avg       0.98      0.99      0.99     87702

ROC 0.9595901216220409

Decision Tree
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     86844
           1       0.36      0.37      0.37       858

    accuracy                           0.99     87702
   macro avg       0.68      0.68      0.68     87702
weighted avg       0.99      0.99      0.99     87702

ROC 0.7002032836201

Random Forest
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     86844
           1       0.53      0.34      0.42       858

    accuracy                           0.99     87702
   macro avg       0.76      0.67      0.71     87702
weighted avg       0.99      0.99      0.99     87702

ROC 0.9733898505575306

In [36]:
# random forest with class_weight to handle imbalanced

rf_weight= RandomForestClassifier(class_weight='balanced', random_state=42)
rf_weight.fit(X_train,y_train)

y_predict=rf_weight.predict(X_test)
y_predict_proba=rf_weight.predict_proba(X_test)[:,1]

print("Random Forest with class_weight:")
print(classification_report(y_test,y_predict))
print('ROC-AUC:', roc_auc_score(y_test,y_predict_proba))

Random Forest with class_weight:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     86844
           1       0.48      0.38      0.43       858

    accuracy                           0.99     87702
   macro avg       0.74      0.69      0.71     87702
weighted avg       0.99      0.99      0.99     87702

ROC-AUC: 0.9666293761049876

In [37]:
# random forest with SMOTE

from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=42)
X_res,y_res=sm.fit_resample(X_train,y_train)

rf_smote=RandomForestClassifier(random_state=42)
rf_smote.fit(X_train,y_train)

y_pred_smote=rf_smote.predict(X_test)
y_proba_smote=rf_smote.predict_proba(X_test)[:,1]

print("Random Forest with Smote:")
print(classification_report(y_test,y_pred_smote))
print("ROC-AUC:", roc_auc_score(y_test,y_proba_smote))

Random Forest with Smote:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     86844
           1       0.52      0.34      0.41       858

    accuracy                           0.99     87702
   macro avg       0.76      0.67      0.70     87702
weighted avg       0.99      0.99      0.99     87702

ROC-AUC: 0.9754339265359024

In [38]:
# random forest with threshold adjustment

rf_base=RandomForestClassifier(random_state=42)
rf_base.fit(X_train,y_train)


y_proba_base=rf_base.predict_proba(X_test)[:,1]

# set threshold
threshold=0.2
y_pred_thresh=(y_proba_base>=threshold).astype(int)

print(f"Random Forest with threshold {threshold}:")
print(classification_report(y_test,y_pred_thresh))
print('ROC-AUC:',roc_auc_score(y_test,y_proba_base))

Random Forest with threshold 0.2:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     86844
           1       0.38      0.52      0.44       858

    accuracy                           0.99     87702
   macro avg       0.69      0.76      0.72     87702
weighted avg       0.99      0.99      0.99     87702

ROC-AUC: 0.9754339265359024

In [39]:
# combination

X=final_data.drop(columns =['ID', 'TARGET', 'worst_status', 'overdue_count', 'overdue_rate'])
y=final_data['TARGET']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# random forest with class_weight to handle imbalanced
rf_weight= RandomForestClassifier(class_weight='balanced', random_state=42)
rf_weight.fit(X_train,y_train)

# random forest with SMOTE
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=42)
X_res,y_res=sm.fit_resample(X_train,y_train)


# random forest with threshold adjustment
rf_base=RandomForestClassifier(random_state=42)
rf_base.fit(X_train,y_train)
y_proba=rf_base.predict_proba(X_test)[:,1]

# set threshold
threshold=0.2
y_pred=(y_proba_base>=threshold).astype(int)

from sklearn.metrics import classification_report, roc_auc_score
print("=== Random Forest 3 Combinations")
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))

=== Random Forest 3 Combinations
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     86844
           1       0.38      0.52      0.44       858

    accuracy                           0.99     87702
   macro avg       0.69      0.76      0.72     87702
weighted avg       0.99      0.99      0.99     87702

ROC-AUC: 0.9754339265359024

### Insights:
    -Threshold adjustment (0.2) significantly increases recall for risky customers (Class 1).
    -Precision for Class 1 drops because the model predicts more positives (trade-off).
    -SMOTE and class_weight did not significantly improve over threshold adjustment in this dataset — threshold dominates the effect.
Overall, model can be used to screen potential risky applicants effectively.

In [41]:
# feature importance
feat_importances = pd.Series(rf_base.feature_importances_, index=X.columns)
feat_importances = feat_importances.sort_values(ascending=False)
print(feat_importances.head(10))  # top 10 features

record_count        0.395132
DAYS_BIRTH          0.132236
DAYS_EMPLOYED       0.098950
AMT_INCOME_TOTAL    0.096696
CNT_FAM_MEMBERS     0.022210
FLAG_PHONE          0.018016
FLAG_OWN_CAR        0.017413
CNT_CHILDREN        0.016414
INC_Working         0.014665
FLAG_WORK_PHONE     0.012992
dtype: float64

In [43]:
# save trained model
import joblib
joblib.dump(rf_base, "rf_model.pkl")

['rf_model.pkl']